ateam-chat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework import routers
from rest_framework.renderers import CoreJSONRenderer
from rest_framework.schemas import get_schema_view
from rest_framework_swagger import renderers


class JSONOpenAPIRenderer(renderers.OpenAPIRenderer):
    media_type = 'application/json'


schema_view = get_schema_view(title='Ateam Chat API', renderer_classes=[CoreJSONRenderer,
                                                                        JSONOpenAPIRenderer,
                                                                        renderers.OpenAPIRenderer,
                                                                        renderers.SwaggerUIRenderer])
router = routers.DefaultRouter()

urlpatterns = [

    url(r'', include('users.urls')),
    url(r'^chat/', include('chat.urls')),

    url(r'^admin/', admin.site.urls),
    # url(r'^rest-api/', include('rest_framework.urls')),

]

chat/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$',  views.about, name='about'),
    url(r'^new/$', views.new_room, name='new_room'),
    url(r'^(?P<label>[\w-]{,50})/$', views.chat_room, name='chat_room'),
]

users/urls.py
from django.conf.urls import include, url
from users.views import LoginView, SignupView, LandingView, LogoutView, username_dup_check

urlpatterns = [
    url(r'^$', LandingView.as_view(), name='landing'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^signup/$', SignupView.as_view(), name='signup'),
    url(r'^available-username/$', username_dup_check, name='username_check'),
]

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import models as auth_models
from django.contrib.auth.models import UserManager as AuthUserManager, User
from django.core import validators
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class User(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):

    username = models.CharField(
        verbose_name=_('username'), unique=True,
        max_length=32,
        help_text='필수입니다. 영문소문자, 숫자와 밑줄(_)만 입력가능합니다.',
        validators=[
            validators.MinLengthValidator(3),
            validators.MaxLengthValidator(32),
            validators.RegexValidator(
                r'^(?!_)[a-zA-Z0-9_]+$',
                '영문소문자, 숫자와 밑줄(_)만 입력가능합니다.',
                'invalid')])
    name = models.CharField(verbose_name='이름', max_length=50)
    display_name = models.CharField(verbose_name='닉네임', max_length=20, blank=False)
    email = models.EmailField(verbose_name='이메일', max_length=190, db_index=True)
    phone = models.CharField('연락처', max_length=30, db_index=True,
                             validators=[validators.RegexValidator(
                                 r'^[0-9]+$',
                                 '숫자만 입력 가능합니다.',
                                 'invalid')])
    date_joined = models.DateTimeField(verbose_name='가입일', default=timezone.now)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = AuthUserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        is_new = not self.id
        if is_new:
            self.subscription_updated_at = self.date_joined
        super(User, self).save(*args, **kwargs)

    def get_full_name(self):
        return self.name.strip()

    def get_short_name(self):
        return self.name.strip()

users/forms.py
import re

from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth import authenticate, get_user_model


User = get_user_model()


EMAIL_DOMAIN_CHOICES = (
    ('', '직접 입력'),
    ('hanmail.net', 'hanmail.net'),
    ('daum.net', 'daum.net'),
    ('naver.com', 'naver.com'),
    ('gmail.com', 'gmail.com'),
)


class LoginForm(forms.Form):
    username = forms.CharField(label='ID',
                               max_length=254,
                               widget=forms.TextInput(attrs={
                                   'placeholder': 'ID',
                                   'class': 'form-control'
                               }),
                               error_messages={
                                   'required': 'ID를 입력해주세요.'})
    password = forms.CharField(label='비밀번호',
                               widget=forms.PasswordInput(attrs={
                                   'placeholder': '비밀번호',
                                   'class': 'form-control'
                               }),
                               error_messages={
                                   'required': '비밀번호를 입력해주세요.'})

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        self.user_cache = authenticate(username=username, password=password)
        if self.user_cache is None:
            raise forms.ValidationError('아이디 또는 비밀번호를 잘못 입력하셨습니다.',
                                        code='invalid_login'
                                        )
        return self.cleaned_data

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache


class SignupForm(forms.ModelForm):
    """
    회원가입 form
    """

    password1 = forms.CharField(required=True,
                                max_length=20,
                                label='비밀번호',
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'form-control',
                                        'placeholder': '비밀번호는 6~20자리'}))

    password2 = forms.CharField(required=True,
                                max_length=20,
                                label='비밀번호 재입력',
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'form-control',
                                        'placeholder': '비밀번호 재입력 6~20자리'}))
    email_name = forms.CharField(label='이메일',
                                 required=True,
                                 max_length=50,
                                 widget=forms.TextInput(
                                     attrs={
                                         'class': 'form-control',
                                         'placeholder': '이메일'
                                     }))
    email_domain = forms.CharField(required=True,
                                   max_length=50,
                                   widget=forms.TextInput(
                                       attrs={
                                           'class': 'form-control',
                                           'placeholder': '직접 입력'}))

    email_domain_choice = forms.ChoiceField(required=False,
                                            choices=EMAIL_DOMAIN_CHOICES,
                                            widget=forms.Select(
                                                attrs={
                                                    'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'phone', 'name', 'display_name')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder': 'ID는 5자리 이상'}),
            'phone': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder': '연락처'}),
            'name': forms.TextInput(attrs={'class': 'form-control',
                                           'placeholder': '이름'}),
            'display_name': forms.TextInput(attrs={'class': 'form-control',
                                                   'placeholder': '닉네임 최대 20자리'})
        }

    def clean_username(self):
        """
        Checks for existing users with the supplied username.
        """
        username = self.cleaned_data['username']
        if User._default_manager.filter(username__iexact=username).exists():
            raise forms.ValidationError(
                'ID가 이미 존재합니다.'
            )
        return username

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        new_phone = re.sub('\D', '', phone)
        return new_phone

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError(
                '비밀번호가 일치하지 않습니다.')
        return password2

    def clean_redirect_url(self):
        url = self.cleaned_data['redirect_url'].strip()
        return reverse_lazy("account:signup_success")

    def clean(self):
        super(SignupForm, self).clean()
        email_name = self.cleaned_data.get('email_name')
        email_domain = self.cleaned_data.get('email_domain')
        email = "{0}@{1}".format(email_name, email_domain)

        try:
            validators.validate_email(email)
        except ValidationError:
            raise forms.ValidationError(
                self.add_error('email_name', '이메일 주소를 정확히 입력해주세요.'))

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.set_password(self.cleaned_data.get('password1'))
        user.country = self.cleaned_data.get('country')

        email_name = self.cleaned_data.get('email_name')
        email_domain = self.cleaned_data.get('email_domain')
        user.email = "{0}@{1}".format(email_name, email_domain)

        if commit:
            user.save()
        return user

users/views.py
import logging
import json

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (login as auth_login, logout as auth_logout, authenticate)
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_protect

from .models import User
from .forms import LoginForm, SignupForm


log = logging.getLogger(__name__)


class LandingView(generic.TemplateView):

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('about'))
        else:
            return HttpResponseRedirect(reverse('login'))


class LoginView(generic.FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = settings.LOGIN_REDIRECT_URL
    username = None

    def get(self, request, *args, **kwargs):
        self.username = request.GET.get('username')
        if request.user.is_authenticated():
            return redirect(settings.LOGIN_REDIRECT_URL)
        return super(LoginView, self).get(request, *args, **kwargs)

    def get_initial(self):
        initial = super(LoginView, self).get_initial()
        if self.username:
            initial['username'] = self.username
        return initial

    def get_form_kwargs(self):
        kwargs = super(LoginView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        user = form.get_user()
        auth_login(self.request, user)

        msg = '로그인 성공.'
        messages.success(self.request, msg)

        log.info(self.request, menu='user', action='login')
        return redirect(self.get_success_url())

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginView, self).dispatch(request, *args, **kwargs)


class SignupView(generic.FormView):
    form_class = SignupForm
    template_name = 'signup.html'
    success_url = reverse_lazy('about')

    def register_user(self, form):
        user = form.save()
        user = authenticate(username=user.username, password=form.cleaned_data['password1'])
        auth_login(self.request, user)
        return user

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(settings.LOGIN_REDIRECT_URL)
        return super(SignupView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        user = self.register_user(form)
        user.save()
        return redirect(self.get_success_url())


class LogoutView(generic.RedirectView):
    permanent = False

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return HttpResponseRedirect(reverse_lazy('login'))


@ensure_csrf_cookie
@csrf_protect
def username_dup_check(request):
    """
    ID 중복 체크
    """
    is_available = False
    if request.is_ajax():
        username = request.POST.get('username')
        try:
            User.objects.get_by_natural_key(username)
        except User.DoesNotExist:
            is_available = 'true'
        return HttpResponse(json.dumps(is_available),
                            content_type='application/json', status=200)
    return HttpResponse(content_type='application/json', status=400)

users/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
    <meta charset="utf-8">
    <title>로그인</title>
    <link href="{% static 'css/normalize.css' %}" rel="stylesheet">
    <link href="{% static 'css/skeleton.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="{% static 'css/chat.css' %}" rel="stylesheet">
</head>

<body>
<div class="content-area">
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ form.username.label }}</label>
            <div class="col-md-9">{{ form.username }}</div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ form.password.label }}</label>
            <div class="col-md-9">{{ form.password }}</div>
        </div>
        {% if form.non_field_errors %}
            <div class="form-group">
                <small class="text-error text-red">
                    {{ form.non_field_errors }}
                </small>
            </div>
        {% endif %}
        <div class="text-center">
            <input type="submit" value="로그인"/>
            <a class="button button-primary" href="{% url 'signup' %}">회원가입</a>
        </div>
    </form>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script>
    $(function () {
        bindEvent();
    });

    function bindEvent() {
        $("#id_username, #id_password").keyup(function () {
            $(".text-error").text("");
        });
    }
</script>
</body>
</html>

users/templates/signup.html
<!DOCTYPE html>
<html lang="en">
{% load static from staticfiles %}
<head>
    <meta charset="utf-8">
    <title>회원가입</title>
    <link href="{% static 'css/normalize.css' %}" rel="stylesheet">
    <link href="{% static 'css/skeleton.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="{% static 'css/chat.css' %}" rel="stylesheet">
</head>

<body>
<div class="content-area">
    <form method="post" action="" id="signUpForm">
        {% csrf_token %}
        <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ form.username.label }}</label>
            <div class="col-md-9">{{ form.username }}
                <div id="{{ form.username.id_for_label }}-error" class="text-red"></div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ form.phone.label }}</label>
            <div class="col-md-9">{{ form.phone }}
                <div id="{{ form.phone.id_for_label }}-error" class="text-red"></div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ form.name.label }}</label>
            <div class="col-md-9">{{ form.name }}
                <div id="{{ form.name.id_for_label }}-error" class="text-red"></div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ form.display_name.label }}</label>
            <div class="col-md-9">{{ form.display_name }}
                <div id="{{ form.display_name.id_for_label }}-error" class="text-red"></div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ form.password1.label }}</label>
            <div class="col-md-9">{{ form.password1 }}
                <div id="{{ form.password1.id_for_label }}-error" class="text-red"></div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ form.password2.label }}</label>
            <div class="col-md-9">{{ form.password2 }}
                <div id="{{ form.password2.id_for_label }}-error" class="text-red"></div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-md-3 col-form-label">{{ form.email_name.label }}</label>
            <div class="col-md-3">{{ form.email_name }}</div>
            <div class="col-md-3">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="emailAddOn">@</span>
                    </div>
                    {{ form.email_domain }}
                </div>
            </div>
            <div class="col-md-3">{{ form.email_domain_choice }}</div>
            <div class="col-md-9 offset-3">
                {% for error in form.email_name.errors %}
                    <p class="text-error">{{ error }}</p>
                {% endfor %}

                <div id="id_email-error" class="text-red"></div>
                <div id="{{ form.email_name.id_for_label }}-error" class="text-red"></div>
                <div id="{{ form.email_domain.id_for_label }}-error" class="text-red"></div>
            </div>
        </div>
        <div class="text-center"><input type="submit" value="회원가입" class="button button-primary"/></div>
    </form>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.validate.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script>
    $(function () {
        bindEvent();
        initSignup();
    });

    function bindEvent() {
        $("#id_email_name, #id_email_domain").keyup(function () {
            $("#id_email-error, #id_email_name-error, #id_email_domain-error").text("");
        });

        $('#id_email_domain_choice').on('change', function () {
            var value = $(this).val();
            $('#id_email_domain').val(value).trigger("keyup");
        });
    }
    function initSignup() {
        $.validator.addMethod(
            "regex",
            function (value, element, regexp) {
                var re = new RegExp(regexp);
                return this.optional(element) || re.test(value);
            }
        );

        $("#signUpForm").validate({
            rules: {
                phone: {
                    required: true
                },

                name: {
                    required: true,
                    maxlength: 50
                },

                username: {
                    required: true,
                    rangelength: [5, 32],
                    regex: /^[a-zA-Z0-9_]+$/,
                    remote: {
                        url: "{% url 'username_check' %}",
                        type: "post",
                        data: {
                            username: function () {
                                return $("#id_username").val();
                            }
                        }
                    }
                },
                display_name: {
                    required: true
                },
                password1: {
                    required: true,
                    rangelength: [6, 20]
                },

                password2: {
                    required: true,
                    equalTo: '#id_password1'
                },

                email_name: {
                    required: true,
                    maxlength: 50
                },
                email_domain: {
                    required: true,
                    maxlength: 50
                }
            },
            messages: {
                phone: {
                    required: '연락처는 필수 입력항목입니다.'
                },

                name: {
                    required: '이름은 필수 입력항목입니다.'
                },

                email_name: {
                    required: '이메일은 필수 입력항목입니다.',
                    maxlength: '최대 입력 길이를 초과하였습니다.'

                },
                email_domain: {
                    required: '이메일은 필수 입력항목입니다.',
                    maxlength: '최대 입력 길이를 초과하였습니다.'
                },

                username: {
                    rangelength: '5~32자 영문소문자, 숫자와 밑줄(_)만 입력가능합니다.',
                    regex: '5~32자 영문소문자, 숫자와 밑줄(_)만 입력가능합니다.',
                    required: 'ID는 필수 입력항목입니다.',
                    remote: '중복된 ID 입니다.'
                },

                display_name: {
                    required: '닉네임은 필수 입력항목입니다.'
                },

                password1: {
                    required: '비밀번호는 필수 입력항목입니다.',
                    rangelength: '비밀번호는 6~20자리로 사용 가능합니다.'
                },

                password2: {
                    required: '비밀번호 재입력은 필수 입력항목입니다.',
                    equalTo: '비밀번호가 일치하지 않습니다.'
                }
            },

            highlight: function (element) {
                $(element).parent().removeClass('has-success').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).parent().removeClass('has-error').addClass('has-success');
            },
            errorElement: 'p',
            errorClass: 'text-error',
            errorPlacement: function (error, element) {
                if (element.length) {
                    if (element.attr('name') == "email_name" || element.attr('name') == "email_domain") {
                        $('#id_email-error').html(error);
                    }
                    else {
                        $('#' + element.attr('id') + '-error').html(error);
                    }

                } else {
                    error.insertAfter(element.parent());
                }
            }
        });

    }
</script>

</body>
</html>